# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarkilar',
            name='favori_mi',
            field=models.BooleanField(default=False),
        ),
    ]
